export const FETCH_FORMS_REQUEST = "FETCH_FORMS_REQUEST";
export const FETCH_FORMS_SUCCESS = "FETCH_FORMS_SUCCESS";
export const FETCH_FORMS_FAILURE = "FETCH_FORMS_FAILURE";

export const SUBMIT_FORMS_REQUEST = "SUBMIT_FORMS_REQUEST";
export const SUBMIT_FORMS_SUCCESS = "SUBMIT_FORMS_SUCCESS";
export const SUBMIT_FORMS_FAILURE = "SUBMIT_FORMS_FAILURE";

export const DELETE_FORMS_REQUEST = "DELETE_FORMS_REQUEST";
export const DELETE_FORMS_SUCCESS = "DELETE_FORMS_SUCCESS";
export const DELETE_FORMS_FAILURE = "DELETE_FORMS_FAILURE";

export const UPDATE_FORMS_REQUEST = "UPDATE_FORMS_REQUEST";
export const UPDATE_FORMS_SUCCESS = "UPDATE_FORMS_SUCCESS";
export const UPDATE_FORMS_FAILURE = "UPDATE_FORMS_FAILURE";
